language: python
python:
 - "3.6"
 - "3.7"
install:
 - pip install codecov
script:
 - python -m unittest testFunction2.py
 - coverage run testFunction2.py
after_success:  bash <(curl -s https://codecov.io/bash)
